version: "3.8"

services:
  backend:
    container_name: fast-api-project
    build:
      context: .
      args:
        - FOR_DEVELOPMENT=true
      dockerfile: src/Dockerfile
    command: bash -c "poetry run alembic upgrade heads && uvicorn backend.asgi:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./src:/app
    env_file:
      - .env
    ports:
      - 4556:8000
    depends_on:
      - db
      - redis

  db:
    container_name: fa-db
    image: postgres:13.3
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - psgr-data:/var/lib/postgresql/data

  redis:
    container_name: fa-redis
    restart: always
    image: redis:7.2.0-alpine
    expose:
     - 6379

volumes:
  psgr-data:

networks:
  default:
    name: network0123
